'use client';
import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type Lang = 'ms' | 'en' | 'zh';

export interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'zh',
  setLang: () => {},
  t: (key) => key,
});

// ─── Translations ────────────────────────────────────────────────────────────
const translations: Record<Lang, Record<string, string>> = {
  ms: {
    // Nav
    'nav.dashboard': 'Papan Pemuka',
    'nav.hotelBooking': 'Tempahan Hotel',
    'nav.pastBookings': 'Sejarah Tempahan',
    'nav.withdrawalTracker': 'Penjejak Pengeluaran',
    'nav.walletTopup': 'Tambah Nilai Dompet',
    'nav.walletWithdrawal': 'Pengeluaran Dompet',
    'nav.userManagement': 'Pengurusan Pengguna',
    'nav.finance': 'Kewangan Admin',
    'nav.hotelManagement': 'Pengurusan Hotel',
    'nav.adminAccounts': 'Akaun Admin',
    'nav.adminMessages': 'Mesej Dalaman',
    'nav.hotelImport': 'Import Hotel Sampel',
    'nav.analytics': 'Analitik Admin',
    'nav.signOut': 'Log Keluar',
    'nav.mainMenu': 'Menu Utama',
    'nav.adminPanel': 'Panel Admin',

    // Topbar
    'topbar.wallet': 'Dompet',
    'topbar.islamicBooking': '🕌 IslamicBooking Pro',
    'topbar.adminPanel': '🛡️ Panel Admin',

    // Dashboard
    'dashboard.title': 'Papan Pemuka',
    'dashboard.welcome': 'Selamat Datang',
    'dashboard.walletBalance': 'Baki Dompet',
    'dashboard.totalCommission': 'Jumlah Komisen',
    'dashboard.totalOrders': 'Jumlah Pesanan',
    'dashboard.reputation': 'Reputasi',
    'dashboard.level': 'Tahap',
    'dashboard.tasks': 'Tugasan',
    'dashboard.recentOrders': 'Pesanan Terkini',
    'dashboard.liveFeed': 'Suapan Langsung',
    'dashboard.withdraw': 'Keluarkan',
    'dashboard.topUp': 'Tambah Nilai',
    'dashboard.bookNow': 'Tempah Sekarang',
    'dashboard.walletHistory': 'Sejarah Dompet',
    'dashboard.commissionChart': 'Carta Komisen',
    'dashboard.levelProgress': 'Kemajuan Tahap',
    'dashboard.ordersToNextLevel': 'pesanan ke tahap seterusnya',
    'dashboard.reputationScore': 'Skor Reputasi',
    'dashboard.canWithdraw': 'Boleh Keluarkan',
    'dashboard.cannotWithdraw': 'Tidak Boleh Keluarkan',
    'dashboard.reputationWarning': 'Reputasi < 80 — tidak boleh keluarkan',
    'dashboard.hotel': 'Hotel',
    'dashboard.amount': 'Jumlah',
    'dashboard.commission': 'Komisen',
    'dashboard.status': 'Status',
    'dashboard.date': 'Tarikh',
    'dashboard.completed': 'Selesai',
    'dashboard.bonus': 'Bonus',
    'dashboard.locked': 'Terkunci',
    'dashboard.inProgress': 'Dalam Proses',
    'dashboard.cancelled': 'Dibatalkan',
    'dashboard.taskProgress': 'Kemajuan Tugasan',
    'dashboard.reward': 'Ganjaran',
    'dashboard.done': 'Selesai',
    'dashboard.pending': 'Belum Selesai',
    'dashboard.viewAll': 'Lihat Semua',
    'dashboard.noOrders': 'Tiada pesanan',

    // Hotel Booking
    'booking.title': 'Tempahan Hotel',
    'booking.selectHotel': 'Pilih Hotel',
    'booking.nights': 'Malam',
    'booking.totalAmount': 'Jumlah Bayaran',
    'booking.commission': 'Komisen',
    'booking.bookNow': 'Tempah Sekarang',
    'booking.minDays': 'Min. Malam',
    'booking.perNight': '/ malam',
    'booking.halalCertified': 'Halal Bersijil',
    'booking.processing': 'Memproses Tempahan...',
    'booking.success': 'Tempahan Berjaya!',
    'booking.bonusOrder': 'Pesanan Bonus',
    'booking.bonusMessage': 'Tahniah! Anda dipilih untuk pesanan bonus.',
    'booking.selectBonusHotel': 'Pilih hotel untuk pesanan bonus anda:',
    'booking.insufficientBalance': 'Baki tidak mencukupi',
    'booking.walletBalance': 'Baki Dompet',
    'booking.searchHotel': 'Cari hotel...',
    'booking.allHotels': 'Semua Hotel',
    'booking.rating': 'Penilaian',
    'booking.location': 'Lokasi',
    'booking.confirmBooking': 'Sahkan Tempahan',
    'booking.cancel': 'Batal',
    'booking.confirm': 'Sahkan',
    'booking.orderSummary': 'Ringkasan Pesanan',
    'booking.originalOrder': 'Pesanan Asal',
    'booking.bonusOrderLabel': 'Pesanan Bonus',
    'booking.totalCommission': 'Jumlah Komisen',
    'booking.fundsUnlocked': 'Dana Dibebaskan',
    'booking.close': 'Tutup',

    // Past Bookings
    'pastBookings.title': 'Sejarah Tempahan',
    'pastBookings.subtitle': 'Rekod semua tempahan anda',
    'pastBookings.totalBookings': 'Jumlah Tempahan',
    'pastBookings.totalPaid': 'Jumlah Dibayar',
    'pastBookings.totalCommission': 'Jumlah Komisen',
    'pastBookings.hotel': 'Hotel',
    'pastBookings.checkIn': 'Daftar Masuk',
    'pastBookings.checkOut': 'Daftar Keluar',
    'pastBookings.nights': 'Malam',
    'pastBookings.amountPaid': 'Jumlah Dibayar',
    'pastBookings.commission': 'Komisen',
    'pastBookings.status': 'Status',
    'pastBookings.orderDate': 'Tarikh Pesanan',
    'pastBookings.all': 'Semua',
    'pastBookings.completed': 'Selesai',
    'pastBookings.bonus': 'Bonus',
    'pastBookings.locked': 'Terkunci',
    'pastBookings.inProgress': 'Dalam Proses',
    'pastBookings.cancelled': 'Dibatalkan',
    'pastBookings.search': 'Cari hotel atau ID...',
    'pastBookings.noResults': 'Tiada rekod ditemui',
    'pastBookings.backToDashboard': 'Kembali ke Papan Pemuka',
    'pastBookings.pendingCompletion': 'Belum Selesai',
    'pastBookings.pendingDesc': 'Pesanan bonus yang belum diselesaikan',
    'pastBookings.noPending': 'Tiada pesanan tertangguh',
    'pastBookings.awaitingCompletion': 'Menunggu Selesai',
    'pastBookings.matchedAt': 'Dipadankan pada',
    'pastBookings.continueOrder': 'Teruskan Pesanan',
    'pastBookings.resumeBonusTitle': 'Teruskan Pesanan Bonus',
    'pastBookings.resumeBonusDesc': 'Pesanan bonus anda sedang menunggu. Teruskan untuk mendapatkan komisen.',
    'pastBookings.processingBonus': 'Memproses Pesanan Bonus...',
    'pastBookings.bonusComplete': 'Pesanan Bonus Selesai!',
    'pastBookings.bonusCompleteDesc': 'Komisen telah ditambah ke dompet anda.',
    'pastBookings.cancelBtn': 'Batal',
    'pastBookings.done': 'Selesai',

    // Withdrawal Tracker
    'withdrawal.title': 'Penjejak Pengeluaran',
    'withdrawal.subtitle': 'Jejak semua permintaan pengeluaran anda',
    'withdrawal.totalApproved': 'Jumlah Diluluskan',
    'withdrawal.pendingAmount': 'Jumlah Tertangguh',
    'withdrawal.totalRequests': 'Jumlah Permintaan',
    'withdrawal.submittedDate': 'Tarikh Hantar',
    'withdrawal.amount': 'Jumlah',
    'withdrawal.status': 'Status',
    'withdrawal.approvalDate': 'Tarikh Lulus',
    'withdrawal.paymentDetails': 'Butiran Pembayaran',
    'withdrawal.bank': 'Bank',
    'withdrawal.accountNo': 'No. Akaun',
    'withdrawal.accountHolder': 'Pemegang Akaun',
    'withdrawal.referenceNo': 'No. Rujukan',
    'withdrawal.remarks': 'Catatan',
    'withdrawal.all': 'Semua',
    'withdrawal.approved': 'Diluluskan',
    'withdrawal.inProcess': 'Dalam Proses',
    'withdrawal.pending': 'Menunggu',
    'withdrawal.rejected': 'Ditolak',
    'withdrawal.noResults': 'Tiada rekod ditemui',
    'withdrawal.backToDashboard': 'Kembali ke Papan Pemuka',
    'withdrawal.viewDetails': 'Lihat Butiran',
    'withdrawal.hideDetails': 'Sembunyikan',
    'withdrawal.na': 'T/A',
    'withdrawal.pending_approval': 'Menunggu Kelulusan',
    'withdraw.accountNoRequired': 'Sila masukkan nombor akaun anda',
    'withdraw.amountRequired': 'Jumlah pengeluaran minimum ialah RM 50',
    'withdraw.insufficientBalance': 'Baki tidak mencukupi',
    'withdraw.bankRequired': 'Sila pilih bank anda',
    'withdraw.accountHolderRequired': 'Sila masukkan nama pemegang akaun',
    'withdraw.holderNameRequired': 'Sila masukkan nama pemegang akaun',
    'withdraw.title': 'Pengeluaran Dompet',
    'withdraw.amount': 'Jumlah Pengeluaran',
    'withdraw.selectBank': 'Pilih Bank',
    'withdraw.selectBankPlaceholder': 'Pilih bank anda',
    'withdraw.accountNumber': 'Nombor Akaun',
    'withdraw.holderName': 'Nama Pemegang Akaun',
    'withdraw.holderNamePlaceholder': 'Nama penuh seperti dalam akaun bank',
    'withdraw.submit': 'Hantar Permintaan',
    'withdraw.submittedTitle': 'Permintaan Dihantar!',
    'withdraw.submittedDesc': 'Permintaan pengeluaran anda telah dihantar kepada admin untuk semakan.',
    'withdraw.done': 'Selesai',

    // Top-Up
    'topup.title': 'Tambah Nilai Dompet',
    'topup.subtitle': 'Hantar permintaan tambah nilai — admin akan menyemak dan mengkreditkan dompet anda',
    'topup.stepDetails': 'Butiran',
    'topup.stepReview': 'Semak',
    'topup.stepDone': 'Selesai',
    'topup.amountSection': 'Jumlah Tambah Nilai',
    'topup.amountMin': 'Jumlah tambah nilai minimum ialah RM 10',
    'topup.methodRequired': 'Sila pilih kaedah pembayaran',
    'topup.bankRequired': 'Sila pilih bank anda',
    'topup.paymentMethod': 'Kaedah Pembayaran',
    'topup.amountTitle': 'Jumlah Tambah Nilai',
    'topup.amountPlaceholder': '0.00',
    'topup.amountError': 'Jumlah tambah nilai minimum ialah RM 10',
    'topup.methodTitle': 'Kaedah Pembayaran',
    'topup.methodError': 'Sila pilih kaedah pembayaran',
    'topup.selectBank': 'Pilih Bank Anda',
    'topup.selectBankPlaceholder': '— Pilih bank —',
    'topup.bankError': 'Sila pilih bank anda',
    'topup.referenceSection': 'Rujukan Transaksi',
    'topup.referenceTitle': 'Rujukan Transaksi',
    'topup.referenceOptional': '(pilihan)',
    'topup.referencePlaceholder': 'Contoh: TXN123456789',
    'topup.receiptSection': 'Muat Naik Resit',
    'topup.receiptTitle': 'Muat Naik Resit',
    'topup.receiptOptional': '(pilihan)',
    'topup.receiptUploaded': 'Dimuat Naik',
    'topup.receiptClickUpload': 'Klik untuk muat naik resit',
    'topup.receiptFormats': 'JPG, PNG atau PDF',
    'topup.clickToUpload': 'Klik untuk muat naik resit',
    'topup.uploadFormats': 'JPG, PNG atau PDF',
    'topup.uploaded': 'Dimuat Naik',
    'topup.continueBtn': 'Semak Permintaan',
    'topup.reviewRequest': 'Semak Permintaan',
    'topup.reviewTitle': 'Semak Permintaan Anda',
    'topup.reviewAmountLabel': 'Jumlah Tambah Nilai',
    'topup.reviewMethodLabel': 'Kaedah Pembayaran',
    'topup.reviewReferenceLabel': 'Rujukan',
    'topup.reviewReceiptLabel': 'Resit',
    'topup.reviewStatusLabel': 'Status selepas hantar',
    'topup.reviewReceiptNone': 'Tidak disediakan',
    'topup.reviewStatusPending': 'Menunggu Semakan',
    'topup.reviewInfoMsg': 'Permintaan anda akan disemak oleh admin. Baki dompet akan dikreditkan setelah diluluskan.',
    'topup.back': 'Kembali',
    'topup.backBtn': 'Kembali',
    'topup.submitRequest': 'Hantar Permintaan',
    'topup.submitBtn': 'Hantar Permintaan',
    'topup.submitting': 'Menghantar...',
    'topup.submittingBtn': 'Menghantar...',
    'topup.submittedTitle': 'Permintaan Dihantar!',
    'topup.submittedDesc': 'Permintaan tambah nilai anda sebanyak',
    'topup.submittedDesc2': 'telah dihantar kepada admin untuk semakan.',
    'topup.successTitle': 'Permintaan Dihantar!',
    'topup.successDesc': 'Permintaan tambah nilai anda sebanyak',
    'topup.successDescSuffix': 'telah dihantar kepada admin untuk semakan.',
    'topup.requestId': 'ID Permintaan',
    'topup.requestIdLabel': 'ID Permintaan',
    'topup.adminReviewMsg': '⏱ Admin akan menyemak permintaan anda dalam masa 1–24 jam. Anda akan diberitahu setelah diluluskan.',
    'topup.pendingNotice': '⏱ Admin akan menyemak permintaan anda dalam masa 1–24 jam. Anda akan diberitahu setelah diluluskan.',
    'topup.submitAnother': 'Hantar Permintaan Lain',
    'topup.submitAnotherBtn': 'Hantar Permintaan Lain',
    'topup.historyTitle': 'Sejarah Tambah Nilai Saya',
    'topup.noHistory': 'Tiada permintaan tambah nilai lagi',
    'topup.historyEmpty': 'Tiada permintaan tambah nilai lagi',
    'topup.statusApproved': 'Diluluskan',
    'topup.statusPending': 'Menunggu',
    'topup.statusRejected': 'Ditolak',
    'topup.toastLoginRequired': 'Sila log masuk untuk menghantar permintaan tambah nilai',
    'topup.toastSuccess': 'Permintaan tambah nilai berjaya dihantar!',
    'topup.toastFailed': 'Gagal menghantar permintaan tambah nilai',
    'topup.enterAmountDesc': 'Masukkan jumlah yang ingin anda tambah nilai ke dalam dompet anda.',
    'topup.depositAmount': 'Jumlah Deposit',
    'topup.continue': 'Teruskan',
    'topup.waitingTitle': 'Menunggu Maklumat Bank',
    'topup.waitingDesc': 'Admin akan memberikan maklumat bank untuk pemindahan anda.',
    'topup.supportedBanks': 'Bank yang disokong:',
    'topup.adminWillProvide': 'Admin akan memberikan nombor akaun bank selepas anda menghantar jumlah.',
    'topup.bankInfoReceived': 'Maklumat Bank Diterima',
    'topup.bankName': 'Nama Bank',
    'topup.accountNumber': 'Nombor Akaun',
    'topup.accountHolder': 'Nama Pemegang',
    'topup.transferAmount': 'Jumlah Pemindahan',
    'topup.uploadReceipt': 'Muat Naik Resit',
    'topup.pleaseUploadReceipt': 'Sila muat naik resit pembayaran anda',
    'topup.receiptSubmitted': 'Resit berjaya dihantar!',
    'topup.submitReceipt': 'Hantar Resit',
    'topup.reviewNotice': '⏱ Admin akan menyemak resit anda dan mengkreditkan dompet anda dalam masa 1–24 jam.',
    'topup.done': 'Selesai',

    // Admin
    'admin.users': 'Pengguna',
    'admin.search': 'Cari...',
    'admin.all': 'Semua',
    'admin.active': 'Aktif',
    'admin.frozen': 'Beku',
    'admin.level': 'Tahap',
    'admin.wallet': 'Dompet',
    'admin.reputation': 'Reputasi',
    'admin.orders': 'Pesanan',
    'admin.status': 'Status',
    'admin.actions': 'Tindakan',
    'admin.freeze': 'Bekukan',
    'admin.unfreeze': 'Aktifkan',
    'admin.editWallet': 'Edit Dompet',
    'admin.editReputation': 'Edit Reputasi',
    'admin.save': 'Simpan',
    'admin.cancel': 'Batal',
    'admin.topupRequests': 'Permintaan Top-Up',
    'admin.withdrawalRequests': 'Permintaan Pengeluaran',
    'admin.walletLogs': 'Log Dompet',
    'admin.approve': 'Luluskan',
    'admin.reject': 'Tolak',
    'admin.process': 'Proses',
    'admin.hotels': 'Hotel',
    'admin.addHotel': 'Tambah Hotel',
    'admin.editHotel': 'Edit Hotel',
    'admin.deleteHotel': 'Padam Hotel',
    'admin.globalSettings': 'Tetapan Global',
    'admin.bonusEligible': 'Layak Bonus',
    'admin.pricePerNight': 'Harga / Malam',
    'admin.minDays': 'Min. Hari',
    'admin.commission': 'Komisen',
    'admin.halalTags': 'Tag Halal (pisahkan dengan koma)',

    // Admin User Management
    'admin.totalMembers': 'Jumlah Ahli',
    'admin.activeAccounts': 'Akaun Aktif',
    'admin.frozenAccounts': 'Akaun Beku',
    'admin.lowReputation': 'Reputasi < 80',
    'admin.export': 'Eksport',
    'admin.allStatus': 'Semua Status',
    'admin.allLevel': 'Semua Tahap',
    'admin.searchPlaceholder': 'Cari nama, e-mel, ID pengguna...',
    'admin.user': 'Pengguna',
    'admin.walletBalance': 'Baki Dompet',
    'admin.joinDate': 'Tarikh Daftar',
    'admin.selectedUsers': 'pengguna dipilih',
    'admin.freezeAll': 'Bekukan Semua',
    'admin.showing': 'Menunjukkan',
    'admin.of': 'daripada',
    'admin.users_label': 'pengguna',
    'admin.editWalletTitle': 'Edit Dompet',
    'admin.currentBalance': 'Baki Semasa',
    'admin.operationType': 'Jenis Operasi',
    'admin.addBalance': '+ Tambah Baki',
    'admin.deductBalance': '− Tolak Baki',
    'admin.amount': 'Jumlah (RM)',
    'admin.adminNote': 'Nota Admin',
    'admin.noteDesc': 'Sebab pengubahsuaian dompet untuk rekod',
    'admin.notePlaceholder': 'Contoh: Kelulusan top-up manual, penalti, dll...',
    'admin.updateWallet': 'Kemaskini Dompet',
    'admin.editReputationTitle': 'Edit Reputasi',
    'admin.currentReputation': 'Reputasi Semasa',
    'admin.reputationWarningAdmin': 'Reputasi di bawah 80 akan menyekat pengeluaran wang pengguna ini.',
    'admin.newReputationValue': 'Nilai Reputasi Baharu (0–100)',
    'admin.reasonForChange': 'Sebab Pengubahsuaian',
    'admin.reasonPlaceholder': 'Contoh: Melanggar terma perkhidmatan, bayaran balik, dll...',
    'admin.updateReputation': 'Kemaskini Reputasi',
    'admin.lowReputationBadge': 'reputasi rendah',
    'admin.activateAccount': 'Aktifkan Akaun',
    'admin.freezeAccount': 'Bekukan Akaun',

    // Active Booking Monitor
    'admin.activeBookingMonitor': 'Pemantauan Tempahan Langsung',
    'admin.activeBookingSubtitle': 'Pengguna yang sedang membuat tempahan secara langsung',
    'admin.activeNow': 'Aktif Sekarang',
    'admin.noActiveBookings': 'Tiada Tempahan Aktif',
    'admin.noActiveBookingsDesc': 'Tiada pengguna yang sedang membuat tempahan',
    'admin.bookingNow': 'Sedang Menempah',
    'admin.bookingHotel': 'Hotel',
    'admin.bookingAmount': 'Jumlah',
    'admin.bookingElapsed': 'Masa Berlalu',
    'admin.dispatchBonus': 'Hantar Pesanan Bonus',
    'admin.dispatchBonusTitle': 'Hantar pesanan bonus kepada pengguna ini',
    'admin.blockTransaction': 'Sekat Transaksi',
    'admin.blockTransactionTitle': 'Sekat dan bekukan akaun pengguna ini',
    'admin.bonusDispatched': 'Pesanan Bonus Dihantar',
    'admin.transactionBlocked': 'Transaksi Disekat',

    // Admin Finance
    'admin.financeTitle': 'Pengurusan Kewangan',
    'admin.financeSubtitle': 'Top-up, pengeluaran, dan log transaksi',
    'admin.topupPending': 'top-up menunggu',
    'admin.withdrawalPending': 'pengeluaran menunggu',
    'admin.topupToday': 'Top-Up Hari Ini',
    'admin.withdrawalToday': 'Pengeluaran Hari Ini',
    'admin.pendingApproval': 'Menunggu Kelulusan',
    'admin.commissionRate': 'Kadar Komisen',
    'admin.financialFlow': 'Aliran Kewangan 7 Hari',
    'admin.financialFlowSubtitle': 'Top-up, pengeluaran, dan komisen',
    'admin.globalCommissionSettings': 'Tetapan Komisen Global',
    'admin.globalCommissionDesc': 'Kadar ini digunakan untuk semua hotel',
    'admin.commissionRateLabel': 'Kadar Komisen (%)',
    'admin.currentCommissionDesc': 'Kadar komisen semasa untuk semua tempahan hotel platform ini',
    'admin.topupRequests': 'Permintaan Top-Up',
    'admin.withdrawalRequests': 'Permintaan Pengeluaran',
    'admin.transactionLogs': 'Log Transaksi',
    'admin.method': 'Kaedah',
    'admin.reference': 'Rujukan',
    'admin.date': 'Tarikh',
    'admin.accountNo': 'No. Akaun',
    'admin.sendBankInfo': 'Hantar Maklumat Bank',
    'admin.approveToplup': 'Luluskan Top-Up',
    'admin.rejectRequest': 'Tolak Permintaan',
    'admin.rejectWithdrawal': 'Tolak Pengeluaran',
    'admin.approveWithdrawal': 'Luluskan Pengeluaran',
    'admin.recentTransactionLogs': 'Log Transaksi Terkini',
    'admin.allWalletMovements': 'Semua pergerakan baki dompet pengguna',
    'admin.balance': 'Baki',
    'admin.bankInfoModalTitle': 'Hantar Maklumat Bank',
    'admin.bankInfoTo': 'Kepada',
    'admin.bankInfoDesc': 'Pengguna perlu membuat pemindahan kepada akaun di bawah. Setelah bukti diterima, luluskan top-up mereka.',
    'admin.bankName': 'Nama Bank',
    'admin.accountNumber': 'Nombor Akaun',
    'admin.accountHolderName': 'Nama Pemegang Akaun',
    'admin.additionalInstructions': 'Arahan Tambahan',
    'admin.additionalInstructionsPlaceholder': 'Contoh: Sertakan nama penuh sebagai rujukan...',
    'admin.sendInfo': 'Hantar Maklumat',
    'admin.rejectConfirmTitle': 'Tolak Permintaan?',
    'admin.rejectConfirmDesc': 'Permintaan daripada pengguna ini akan ditolak dan pengguna akan dimaklumkan.',
    'admin.yesReject': 'Ya, Tolak',
    'admin.topup': 'top-up',
    'admin.withdrawal': 'pengeluaran',

    // Admin Hotel Management
    'admin.hotelTitle': 'Pengurusan Hotel',
    'admin.hotelSubtitle': 'hotel · aktif · layak bonus',
    'admin.addHotelBtn': 'Tambah Hotel',
    'admin.editHotelBtn': 'Edit Hotel',
    'admin.deleteHotelBtn': 'Padam Hotel',
    'admin.totalHotels': 'Jumlah Hotel',
    'admin.activeHotels': 'Hotel Aktif',
    'admin.bonusEligibleHotels': 'Layak Bonus',
    'admin.inactiveHotels': 'Tidak Aktif',
    'admin.searchHotelPlaceholder': 'Cari hotel atau lokasi...',
    'admin.allFilter': 'Semua',
    'admin.activeFilter': 'Aktif',
    'admin.inactiveFilter': 'Tidak Aktif',
    'admin.location': 'Lokasi',
    'admin.pricePerNightLabel': 'Harga/Malam',
    'admin.minDaysLabel': 'Min. Hari',
    'admin.commissionLabel': 'Komisen',
    'admin.bonusLabel': 'Bonus',
    'admin.activeLabel': 'Aktif',
    'admin.createdAt': 'Dicipta',
    'admin.editHotelTitle': 'Edit Hotel',
    'admin.addHotelTitle': 'Tambah Hotel Baharu',
    'admin.hotelName': 'Nama Hotel',
    'admin.hotelLocation': 'Lokasi',
    'admin.pricePerNightForm': 'Harga / Malam (RM)',
    'admin.minDaysForm': 'Minimum Hari',
    'admin.commissionForm': 'Kadar Komisen (%)',
    'admin.halalTagsForm': 'Tag Halal (comma separated)',
    'admin.halalTagsPlaceholder': 'Contoh: Makanan Halal, Bilik Solat, Tanpa Alkohol',
    'admin.bonusEligibleForm': 'Layak Pesanan Bonus',
    'admin.activeForm': 'Hotel Aktif',
    'admin.saveHotel': 'Simpan Hotel',
    'admin.updateHotel': 'Kemaskini Hotel',
    'admin.saving': 'Menyimpan...',
    'admin.deleteHotelTitle': 'Padam Hotel?',
    'admin.deleteHotelDesc': 'Hotel ini akan dipadam secara kekal. Tindakan ini tidak boleh dibatalkan.',
    'admin.yesDelete': 'Ya, Padam',
    'admin.globalSettingsTitle': 'Tetapan Global Hotel',
    'admin.globalSettingsDesc': 'Leave any field blank to keep the hotel\'s current value.',
    'admin.globalPriceLabel': 'Harga Global / Malam (RM)',
    'admin.globalMinDaysLabel': 'Min. Hari Global',
    'admin.globalCommissionLabel': 'Kadar Komisen Global (%)',
    'admin.applyToAll': 'Guna pada Semua Hotel',

    // Hotel Booking modal strings
    'booking.bookingDetails': 'Butiran Tempahan',
    'booking.numberOfNights': 'Bilangan Malam',
    'booking.minimumNights': 'Minimum malam untuk hotel ini',
    'booking.nights_label': 'malam',
    'booking.perNightLabel': '/malam',
    'booking.commissionLabel': 'Komisen',
    'booking.totalDeducted': 'Jumlah Ditolak',
    'booking.walletSufficient': 'Mencukupi',
    'booking.walletInsufficient': 'Tidak mencukupi',
    'booking.walletBalanceLabel': 'Baki dompet',
    'booking.proceed': 'Teruskan',
    'booking.processingTitle': 'Memproses Tempahan',
    'booking.processingDesc': 'Menyemak ketersediaan dengan platform antarabangsa...',
    'booking.percentComplete': '% selesai',
    'booking.bookingSuccessTitle': 'Tempahan Berjaya!',
    'booking.orderNo': 'No. Pesanan',
    'booking.totalPaid': 'Jumlah Dibayar',
    'booking.commissionReceived': 'Komisen Diterima',
    'booking.bonusSelectedTitle': 'Anda Dipilih untuk Pesanan Bonus!',
    'booking.bonusSelectedDesc': 'Selesaikan pesanan bonus untuk membuka kunci dana anda',
    'booking.bonusLockedWarning': 'Dana dari pesanan pertama anda TERKUNCI sehingga pesanan bonus ini diselesaikan.',
    'booking.selectBonusHotelLabel': 'Pilih satu hotel untuk pesanan bonus:',
    'booking.bonusCommission': 'Komisen',
    'booking.selectBtn': 'Pilih',
    'booking.bonusCannotSkip': 'Pesanan bonus tidak boleh diabaikan. Hubungi sokongan jika ada masalah.',
    'booking.bonusProcessingTitle': 'Memproses Pesanan Bonus',
    'booking.bonusProcessingDesc': 'Dana pesanan pertama sedang diproses bersama...',
    'booking.bothOrdersComplete': 'Kedua-dua Pesanan Selesai!',
    'booking.bothOrdersDesc': 'Dana terkunci telah dibebaskan · Komisen digabungkan',
    'booking.originalOrderLabel': 'Pesanan Asal',
    'booking.bonusOrderStar': '⭐ Pesanan Bonus',
    'booking.bonusCommissionLabel': 'Komisen Bonus',
    'booking.totalCommissionReceived': 'Jumlah Komisen Diterima',
    'booking.fundsReleasedMsg': 'Dana terkunci sebanyak telah dibebaskan ke dompet anda.',
    'booking.finish': 'Selesai',
    'booking.noHotelFound': 'Tiada Hotel Dijumpai',
    'booking.noHotelDesc': 'Cuba ubah carian atau penapis lokasi anda.',
    'booking.minNightsLabel': 'Min.',
    'booking.commissionShort': 'Komisen',
    'booking.bookBtn': 'Tempah',
    'booking.pendingWarningTitle': 'Anda Mempunyai Pesanan Belum Selesai',
    'booking.pendingWarningDesc': 'Anda mempunyai satu pesanan bonus yang belum diselesaikan. Sila selesaikan pesanan tersebut sebelum membuat tempahan baharu.',
    'booking.goToPendingOrder': 'Pergi ke Pesanan Belum Selesai',
    'booking.bonusTotalPaid': 'Jumlah Dibayar',
    'booking.processingStatus': 'Sedang memproses...',
    'booking.syncingPlatforms': 'Menyegerakkan data platform',
    'booking.processingWait': 'Sedang memproses, sila tunggu...',
    'booking.orderSettlement': 'Maklumat Penyelesaian Pesanan',
    'booking.bonusOrderSettlement': 'Maklumat Penyelesaian Pesanan Bonus',
    'booking.orderComplete': 'Pesanan berjaya diselesaikan',
    'booking.congratsMsg': 'Tahniah! Komisen telah berjaya diselesaikan dan akan dikreditkan dalam masa 24 jam.',
    'booking.hotelName': 'Nama Hotel',
    'booking.orderNumber': 'No. Pesanan',
    'booking.secondsLeft': 's lagi',
    'booking.fullHotel': 'Hotel ini penuh pada masa ini, tidak boleh ditempah.',
    'booking.orderSettlementDetails': 'Butiran Penyelesaian Pesanan',
    'booking.progressLabel': 'Kemajuan Padanan Sistem',
    'booking.fundsReleasedFull': 'Dana terkunci telah dibebaskan ke dompet anda.',

    // Language switcher
    'lang.ms': 'BM',
    'lang.en': 'EN',
    'lang.zh': '中文',
    'lang.label': '语言',
  },

  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.hotelBooking': 'Hotel Booking',
    'nav.pastBookings': 'Past Bookings',
    'nav.withdrawalTracker': 'Withdrawal Tracker',
    'nav.walletTopup': 'Wallet Top-Up',
    'nav.walletWithdrawal': 'Wallet Withdrawal',
    'nav.userManagement': 'User Management',
    'nav.finance': 'Finance',
    'nav.hotelManagement': 'Hotel Management',
    'nav.adminAccounts': 'Admin Accounts',
    'nav.adminMessages': 'Internal Messages',
    'nav.hotelImport': 'Import Sample Hotels',
    'nav.analytics': 'Admin Analytics',
    'nav.signOut': 'Sign Out',
    'nav.mainMenu': 'Main Menu',
    'nav.adminPanel': 'Admin Panel',

    // Topbar
    'topbar.wallet': 'Wallet',
    'topbar.islamicBooking': '🕌 IslamicBooking Pro',
    'topbar.adminPanel': '🛡️ Admin Panel',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.walletBalance': 'Wallet Balance',
    'dashboard.totalCommission': 'Total Commission',
    'dashboard.totalOrders': 'Total Orders',
    'dashboard.reputation': 'Reputation',
    'dashboard.level': 'Level',
    'dashboard.tasks': 'Tasks',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.liveFeed': 'Live Feed',
    'dashboard.withdraw': 'Withdraw',
    'dashboard.topUp': 'Top Up',
    'dashboard.bookNow': 'Book Now',
    'dashboard.walletHistory': 'Wallet History',
    'dashboard.commissionChart': 'Commission Chart',
    'dashboard.levelProgress': 'Level Progress',
    'dashboard.ordersToNextLevel': 'orders to next level',
    'dashboard.reputationScore': 'Reputation Score',
    'dashboard.canWithdraw': 'Can Withdraw',
    'dashboard.cannotWithdraw': 'Cannot Withdraw',
    'dashboard.reputationWarning': 'Reputation < 80 — cannot withdraw',
    'dashboard.hotel': 'Hotel',
    'dashboard.amount': 'Amount',
    'dashboard.commission': 'Commission',
    'dashboard.status': 'Status',
    'dashboard.date': 'Date',
    'dashboard.completed': 'Completed',
    'dashboard.bonus': 'Bonus',
    'dashboard.locked': 'Locked',
    'dashboard.inProgress': 'In Progress',
    'dashboard.cancelled': 'Cancelled',
    'dashboard.taskProgress': 'Task Progress',
    'dashboard.reward': 'Reward',
    'dashboard.done': 'Done',
    'dashboard.pending': 'Pending',
    'dashboard.viewAll': 'View All',
    'dashboard.noOrders': 'No orders',

    // Hotel Booking
    'booking.title': 'Hotel Booking',
    'booking.selectHotel': 'Select Hotel',
    'booking.nights': 'Nights',
    'booking.totalAmount': 'Total Amount',
    'booking.commission': 'Commission',
    'booking.bookNow': 'Book Now',
    'booking.minDays': 'Min. Nights',
    'booking.perNight': '/ night',
    'booking.halalCertified': 'Halal Certified',
    'booking.processing': 'Processing Booking...',
    'booking.success': 'Booking Successful!',
    'booking.bonusOrder': 'Bonus Order',
    'booking.bonusMessage': 'Congratulations! You have been selected for a bonus order.',
    'booking.selectBonusHotel': 'Select a hotel for your bonus order:',
    'booking.insufficientBalance': 'Insufficient balance',
    'booking.walletBalance': 'Wallet Balance',
    'booking.searchHotel': 'Search hotel...',
    'booking.allHotels': 'All Hotels',
    'booking.rating': 'Rating',
    'booking.location': 'Location',
    'booking.confirmBooking': 'Confirm Booking',
    'booking.cancel': 'Cancel',
    'booking.confirm': 'Confirm',
    'booking.orderSummary': 'Order Summary',
    'booking.originalOrder': 'Original Order',
    'booking.bonusOrderLabel': 'Bonus Order',
    'booking.totalCommission': 'Total Commission',
    'booking.fundsUnlocked': 'Funds Unlocked',
    'booking.close': 'Close',

    // Past Bookings
    'pastBookings.title': 'Past Bookings',
    'pastBookings.subtitle': 'Record of all your bookings',
    'pastBookings.totalBookings': 'Total Bookings',
    'pastBookings.totalPaid': 'Total Paid',
    'pastBookings.totalCommission': 'Total Commission',
    'pastBookings.hotel': 'Hotel',
    'pastBookings.checkIn': 'Check In',
    'pastBookings.checkOut': 'Check Out',
    'pastBookings.nights': 'Nights',
    'pastBookings.amountPaid': 'Amount Paid',
    'pastBookings.commission': 'Commission',
    'pastBookings.status': 'Status',
    'pastBookings.orderDate': 'Order Date',
    'pastBookings.all': 'All',
    'pastBookings.completed': 'Completed',
    'pastBookings.bonus': 'Bonus',
    'pastBookings.locked': 'Locked',
    'pastBookings.inProgress': 'In Progress',
    'pastBookings.cancelled': 'Cancelled',
    'pastBookings.search': 'Search hotel or ID...',
    'pastBookings.noResults': 'No records found',
    'pastBookings.backToDashboard': 'Back to Dashboard',
    'pastBookings.pendingCompletion': 'Pending Completion',
    'pastBookings.pendingDesc': 'Bonus orders not yet completed',
    'pastBookings.noPending': 'No pending orders',
    'pastBookings.awaitingCompletion': 'Awaiting Completion',
    'pastBookings.matchedAt': 'Matched at',
    'pastBookings.continueOrder': 'Continue Order',
    'pastBookings.resumeBonusTitle': 'Resume Bonus Order',
    'pastBookings.resumeBonusDesc': 'Your bonus order is waiting. Continue to earn commission.',
    'pastBookings.processingBonus': 'Processing Bonus Order...',
    'pastBookings.bonusComplete': 'Bonus Order Complete!',
    'pastBookings.bonusCompleteDesc': 'Commission has been added to your wallet.',
    'pastBookings.cancelBtn': 'Cancel',
    'pastBookings.done': 'Done',

    // Withdrawal Tracker
    'withdrawal.title': 'Withdrawal Tracker',
    'withdrawal.subtitle': 'Track all your withdrawal requests',
    'withdrawal.totalApproved': 'Total Approved',
    'withdrawal.pendingAmount': 'Pending Amount',
    'withdrawal.totalRequests': 'Total Requests',
    'withdrawal.submittedDate': 'Submitted Date',
    'withdrawal.amount': 'Amount',
    'withdrawal.status': 'Status',
    'withdrawal.approvalDate': 'Approval Date',
    'withdrawal.paymentDetails': 'Payment Details',
    'withdrawal.bank': 'Bank',
    'withdrawal.accountNo': 'Account No.',
    'withdrawal.accountHolder': 'Account Holder',
    'withdrawal.referenceNo': 'Reference No.',
    'withdrawal.remarks': 'Remarks',
    'withdrawal.all': 'All',
    'withdrawal.approved': 'Approved',
    'withdrawal.inProcess': 'In Process',
    'withdrawal.pending': 'Pending',
    'withdrawal.rejected': 'Rejected',
    'withdrawal.noResults': 'No records found',
    'withdrawal.backToDashboard': 'Back to Dashboard',
    'withdrawal.viewDetails': 'View Details',
    'withdrawal.hideDetails': 'Hide',
    'withdrawal.na': 'N/A',
    'withdrawal.pending_approval': 'Pending Approval',
    'withdraw.accountNoRequired': 'Please enter your account number',
    'withdraw.amountRequired': 'Minimum withdrawal amount is RM 50',
    'withdraw.insufficientBalance': 'Insufficient balance',
    'withdraw.bankRequired': 'Please select your bank',
    'withdraw.accountHolderRequired': 'Please enter the account holder name',
    'withdraw.holderNameRequired': 'Please enter the account holder name',
    'withdraw.title': 'Wallet Withdrawal',
    'withdraw.amount': 'Withdrawal Amount',
    'withdraw.selectBank': 'Select Bank',
    'withdraw.selectBankPlaceholder': 'Select your bank',
    'withdraw.accountNumber': 'Account Number',
    'withdraw.holderName': 'Account Holder Name',
    'withdraw.holderNamePlaceholder': 'Full name as per bank account',
    'withdraw.submit': 'Submit Request',
    'withdraw.submittedTitle': 'Request Submitted!',
    'withdraw.submittedDesc': 'Your withdrawal request has been sent to admin for review.',
    'withdraw.done': 'Done',

    // Top-Up
    'topup.title': 'Wallet Top-Up',
    'topup.subtitle': 'Submit a top-up request — admin will review and credit your wallet',
    'topup.stepDetails': 'Details',
    'topup.stepReview': 'Review',
    'topup.stepDone': 'Done',
    'topup.amountSection': 'Top-Up Amount',
    'topup.amountMin': 'Minimum top-up amount is RM 10',
    'topup.methodRequired': 'Please select a payment method',
    'topup.bankRequired': 'Please select your bank',
    'topup.paymentMethod': 'Payment Method',
    'topup.amountTitle': 'Top-Up Amount',
    'topup.amountPlaceholder': '0.00',
    'topup.amountError': 'Minimum top-up amount is RM 10',
    'topup.methodTitle': 'Payment Method',
    'topup.methodError': 'Please select a payment method',
    'topup.selectBank': 'Select Your Bank',
    'topup.selectBankPlaceholder': '— Select bank —',
    'topup.bankError': 'Please select your bank',
    'topup.referenceSection': 'Transaction Reference',
    'topup.referenceTitle': 'Transaction Reference',
    'topup.referenceOptional': '(optional)',
    'topup.referencePlaceholder': 'e.g. TXN123456789',
    'topup.receiptSection': 'Upload Receipt',
    'topup.receiptTitle': 'Upload Receipt',
    'topup.receiptOptional': '(optional)',
    'topup.receiptUploaded': 'Uploaded',
    'topup.receiptClickUpload': 'Click to upload receipt',
    'topup.receiptFormats': 'JPG, PNG or PDF',
    'topup.clickToUpload': 'Click to upload receipt',
    'topup.uploadFormats': 'JPG, PNG or PDF',
    'topup.uploaded': 'Uploaded',
    'topup.continueBtn': 'Review Request',
    'topup.reviewRequest': 'Review Request',
    'topup.reviewTitle': 'Review Your Request',
    'topup.reviewAmountLabel': 'Top-Up Amount',
    'topup.reviewMethodLabel': 'Payment Method',
    'topup.reviewReferenceLabel': 'Reference',
    'topup.reviewReceiptLabel': 'Receipt',
    'topup.reviewStatusLabel': 'Status after submission',
    'topup.reviewReceiptNone': 'Not provided',
    'topup.reviewStatusPending': 'Pending Review',
    'topup.reviewInfoMsg': 'Your request will be reviewed by admin. Wallet balance will be credited once approved.',
    'topup.back': 'Back',
    'topup.backBtn': 'Back',
    'topup.submitRequest': 'Submit Request',
    'topup.submitBtn': 'Submit Request',
    'topup.submitting': 'Submitting...',
    'topup.submittingBtn': 'Submitting...',
    'topup.submittedTitle': 'Request Submitted!',
    'topup.submittedDesc': 'Your top-up request of',
    'topup.submittedDesc2': 'has been sent to admin for review.',
    'topup.successTitle': 'Request Submitted!',
    'topup.successDesc': 'Your top-up request of',
    'topup.successDescSuffix': 'has been sent to admin for review.',
    'topup.requestId': 'Request ID',
    'topup.requestIdLabel': 'Request ID',
    'topup.adminReviewMsg': '⏱ Admin will review your request within 1–24 hours. You will be notified once approved.',
    'topup.pendingNotice': '⏱ Admin will review your request within 1–24 hours. You will be notified once approved.',
    'topup.submitAnother': 'Submit Another Request',
    'topup.submitAnotherBtn': 'Submit Another Request',
    'topup.historyTitle': 'My Top-Up History',
    'topup.noHistory': 'No top-up requests yet',
    'topup.historyEmpty': 'No top-up requests yet',
    'topup.statusApproved': 'Approved',
    'topup.statusPending': 'Pending',
    'topup.statusRejected': 'Rejected',
    'topup.toastLoginRequired': 'Please log in to submit a top-up request',
    'topup.toastSuccess': 'Top-up request submitted successfully!',
    'topup.toastFailed': 'Failed to submit top-up request',
    'topup.enterAmountDesc': 'Enter the amount you wish to top up into your wallet.',
    'topup.depositAmount': 'Deposit Amount',
    'topup.continue': 'Continue',
    'topup.waitingTitle': 'Waiting for Bank Info',
    'topup.waitingDesc': 'Admin will provide bank details for your transfer.',
    'topup.supportedBanks': 'Supported banks:',
    'topup.adminWillProvide': 'Admin will provide the bank account number after you submit the amount.',
    'topup.bankInfoReceived': 'Bank Info Received',
    'topup.bankName': 'Bank Name',
    'topup.accountNumber': 'Account Number',
    'topup.accountHolder': 'Account Holder',
    'topup.transferAmount': 'Transfer Amount',
    'topup.uploadReceipt': 'Upload Receipt',
    'topup.pleaseUploadReceipt': 'Please upload your payment receipt',
    'topup.receiptSubmitted': 'Receipt submitted successfully!',
    'topup.submitReceipt': 'Submit Receipt',
    'topup.reviewNotice': '⏱ Admin will review your receipt and credit your wallet within 1–24 hours.',
    'topup.done': 'Done',

    // Admin
    'admin.users': 'Users',
    'admin.search': 'Search...',
    'admin.all': 'All',
    'admin.active': 'Active',
    'admin.frozen': 'Frozen',
    'admin.level': 'Level',
    'admin.wallet': 'Wallet',
    'admin.reputation': 'Reputation',
    'admin.orders': 'Orders',
    'admin.status': 'Status',
    'admin.actions': 'Actions',
    'admin.freeze': 'Freeze',
    'admin.unfreeze': 'Unfreeze',
    'admin.editWallet': 'Edit Wallet',
    'admin.editReputation': 'Edit Reputation',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.topupRequests': 'Top-Up Requests',
    'admin.withdrawalRequests': 'Withdrawal Requests',
    'admin.walletLogs': 'Wallet Logs',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.process': 'Process',
    'admin.hotels': 'Hotels',
    'admin.addHotel': 'Add Hotel',
    'admin.editHotel': 'Edit Hotel',
    'admin.deleteHotel': 'Delete Hotel',
    'admin.globalSettings': 'Global Settings',
    'admin.bonusEligible': 'Bonus Eligible',
    'admin.pricePerNight': 'Price / Night',
    'admin.minDays': 'Min. Days',
    'admin.commission': 'Commission',
    'admin.halalTags': 'Halal Tags',

    // Admin User Management
    'admin.totalMembers': 'Total Members',
    'admin.activeAccounts': 'Active Accounts',
    'admin.frozenAccounts': 'Frozen Accounts',
    'admin.lowReputation': 'Reputation < 80',
    'admin.export': 'Export',
    'admin.allStatus': 'All Status',
    'admin.allLevel': 'All Level',
    'admin.searchPlaceholder': 'Search name, email, user ID...',
    'admin.user': 'User',
    'admin.walletBalance': 'Wallet Balance',
    'admin.joinDate': 'Join Date',
    'admin.selectedUsers': 'users selected',
    'admin.freezeAll': 'Freeze All',
    'admin.showing': 'Showing',
    'admin.of': 'of',
    'admin.users_label': 'users',
    'admin.editWalletTitle': 'Edit Wallet',
    'admin.currentBalance': 'Current Balance',
    'admin.operationType': 'Operation Type',
    'admin.addBalance': '+ Add Balance',
    'admin.deductBalance': '− Deduct Balance',
    'admin.amount': 'Amount (RM)',
    'admin.adminNote': 'Admin Note',
    'admin.noteDesc': 'Reason for wallet modification for records',
    'admin.notePlaceholder': 'e.g. Manual top-up approval, penalty, etc...',
    'admin.updateWallet': 'Update Wallet',
    'admin.editReputationTitle': 'Edit Reputation',
    'admin.currentReputation': 'Current Reputation',
    'admin.reputationWarningAdmin': 'Reputation below 80 will block this user from withdrawals.',
    'admin.newReputationValue': 'New Reputation Value (0–100)',
    'admin.reasonForChange': 'Reason for Change',
    'admin.reasonPlaceholder': 'e.g. Violated terms of service, refund, etc...',
    'admin.updateReputation': 'Update Reputation',
    'admin.lowReputationBadge': 'low reputation',
    'admin.activateAccount': 'Activate Account',
    'admin.freezeAccount': 'Freeze Account',

    // Active Booking Monitor
    'admin.activeBookingMonitor': 'Live Booking Monitor',
    'admin.activeBookingSubtitle': 'Users currently making bookings in real time',
    'admin.activeNow': 'Active Now',
    'admin.noActiveBookings': 'No Active Bookings',
    'admin.noActiveBookingsDesc': 'No users are currently making bookings',
    'admin.bookingNow': 'Booking Now',
    'admin.bookingHotel': 'Hotel',
    'admin.bookingAmount': 'Amount',
    'admin.bookingElapsed': 'Elapsed Time',
    'admin.dispatchBonus': 'Dispatch Bonus Order',
    'admin.dispatchBonusTitle': 'Dispatch a bonus order to this user',
    'admin.blockTransaction': 'Block Transaction',
    'admin.blockTransactionTitle': 'Block and freeze this user account',
    'admin.bonusDispatched': 'Bonus Order Dispatched',
    'admin.transactionBlocked': 'Transaction Blocked',

    // Admin Finance
    'admin.financeTitle': 'Finance Management',
    'admin.financeSubtitle': 'Top-up, withdrawals, and transaction logs',
    'admin.topupPending': 'top-up pending',
    'admin.withdrawalPending': 'withdrawal pending',
    'admin.topupToday': 'Top-Up Today',
    'admin.withdrawalToday': 'Withdrawal Today',
    'admin.pendingApproval': 'Pending Approval',
    'admin.commissionRate': 'Commission Rate',
    'admin.financialFlow': '7-Day Financial Flow',
    'admin.financialFlowSubtitle': 'Top-up, withdrawals, and commission',
    'admin.globalCommissionSettings': 'Global Commission Settings',
    'admin.globalCommissionDesc': 'This rate applies to all hotels',
    'admin.commissionRateLabel': 'Commission Rate (%)',
    'admin.currentCommissionDesc': 'Current commission rate for all hotel bookings on this platform',
    'admin.topupRequests': 'Top-Up Requests',
    'admin.withdrawalRequests': 'Withdrawal Requests',
    'admin.transactionLogs': 'Transaction Logs',
    'admin.method': 'Method',
    'admin.reference': 'Reference',
    'admin.date': 'Date',
    'admin.accountNo': 'Account No.',
    'admin.sendBankInfo': 'Send Bank Info',
    'admin.approveToplup': 'Approve Top-Up',
    'admin.rejectRequest': 'Reject Request',
    'admin.rejectWithdrawal': 'Reject Withdrawal',
    'admin.approveWithdrawal': 'Approve Withdrawal',
    'admin.recentTransactionLogs': 'Recent Transaction Logs',
    'admin.allWalletMovements': 'All user wallet balance movements',
    'admin.balance': 'Balance',
    'admin.bankInfoModalTitle': 'Send Bank Info',
    'admin.bankInfoTo': 'To',
    'admin.bankInfoDesc': 'User needs to transfer to the account below. Once proof is received, approve their top-up.',
    'admin.bankName': 'Bank Name',
    'admin.accountNumber': 'Account Number',
    'admin.accountHolderName': 'Account Holder Name',
    'admin.additionalInstructions': 'Additional Instructions',
    'admin.additionalInstructionsPlaceholder': 'e.g. Include full name as reference...',
    'admin.sendInfo': 'Send Info',
    'admin.rejectConfirmTitle': 'Reject Request?',
    'admin.rejectConfirmDesc': 'The request from this user will be rejected and the user will be notified.',
    'admin.yesReject': 'Yes, Reject',
    'admin.topup': 'top-up',
    'admin.withdrawal': 'withdrawal',

    // Admin Hotel Management
    'admin.hotelTitle': 'Hotel Management',
    'admin.hotelSubtitle': 'hotels · active · bonus eligible',
    'admin.addHotelBtn': 'Add Hotel',
    'admin.editHotelBtn': 'Edit Hotel',
    'admin.deleteHotelBtn': 'Delete Hotel',
    'admin.totalHotels': 'Total Hotels',
    'admin.activeHotels': 'Active Hotels',
    'admin.bonusEligibleHotels': 'Bonus Eligible',
    'admin.inactiveHotels': 'Inactive',
    'admin.searchHotelPlaceholder': 'Search hotel or location...',
    'admin.allFilter': 'All',
    'admin.activeFilter': 'Active',
    'admin.inactiveFilter': 'Inactive',
    'admin.location': 'Location',
    'admin.pricePerNightLabel': 'Price/Night',
    'admin.minDaysLabel': 'Min. Days',
    'admin.commissionLabel': 'Commission',
    'admin.bonusLabel': 'Bonus',
    'admin.activeLabel': 'Active',
    'admin.createdAt': 'Created',
    'admin.editHotelTitle': 'Edit Hotel',
    'admin.addHotelTitle': 'Add New Hotel',
    'admin.hotelName': 'Hotel Name',
    'admin.hotelLocation': 'Location',
    'admin.pricePerNightForm': 'Price / Night (RM)',
    'admin.minDaysForm': 'Minimum Days',
    'admin.commissionForm': 'Commission Rate (%)',
    'admin.halalTagsForm': 'Halal Tags (comma separated)',
    'admin.halalTagsPlaceholder': 'e.g. Halal Food, Prayer Room, No Alcohol',
    'admin.bonusEligibleForm': 'Bonus Order Eligible',
    'admin.activeForm': 'Hotel Active',
    'admin.saveHotel': 'Save Hotel',
    'admin.updateHotel': 'Update Hotel',
    'admin.saving': 'Saving...',
    'admin.deleteHotelTitle': 'Delete Hotel?',
    'admin.deleteHotelDesc': 'This hotel will be permanently deleted. This action cannot be undone.',
    'admin.yesDelete': 'Yes, Delete',
    'admin.globalSettingsTitle': 'Global Hotel Settings',
    'admin.globalSettingsDesc': 'Leave any field blank to keep the hotel\'s current value.',
    'admin.globalPriceLabel': 'Global Price / Night (RM)',
    'admin.globalMinDaysLabel': 'Global Min. Days',
    'admin.globalCommissionLabel': 'Global Commission Rate (%)',
    'admin.applyToAll': 'Apply to All Hotels',

    // Hotel Booking modal strings
    'booking.bookingDetails': 'Booking Details',
    'booking.numberOfNights': 'Number of Nights',
    'booking.minimumNights': 'Minimum nights for this hotel',
    'booking.nights_label': 'nights',
    'booking.perNightLabel': '/night',
    'booking.commissionLabel': 'Commission',
    'booking.totalDeducted': 'Total Deducted',
    'booking.walletSufficient': 'Sufficient',
    'booking.walletInsufficient': 'Insufficient',
    'booking.walletBalanceLabel': 'Wallet balance',
    'booking.proceed': 'Proceed',
    'booking.processingTitle': 'Processing Booking',
    'booking.processingDesc': 'Checking availability with international platforms...',
    'booking.percentComplete': '% complete',
    'booking.bookingSuccessTitle': 'Booking Successful!',
    'booking.orderNo': 'Order No.',
    'booking.totalPaid': 'Total Paid',
    'booking.commissionReceived': 'Commission Received',
    'booking.bonusSelectedTitle': 'You Have Been Selected for a Bonus Order!',
    'booking.bonusSelectedDesc': 'Complete the bonus order to unlock your funds',
    'booking.bonusLockedWarning': 'Funds from your first order are LOCKED until this bonus order is completed.',
    'booking.selectBonusHotelLabel': 'Select a hotel for your bonus order:',
    'booking.bonusCommission': 'Commission',
    'booking.selectBtn': 'Select',
    'booking.bonusCannotSkip': 'Bonus orders cannot be skipped. Contact support if you have issues.',
    'booking.bonusProcessingTitle': 'Processing Bonus Order',
    'booking.bonusProcessingDesc': 'First order funds are being processed together...',
    'booking.bothOrdersComplete': 'Both Orders Complete!',
    'booking.bothOrdersDesc': 'Locked funds released · Commission combined',
    'booking.originalOrderLabel': 'Original Order',
    'booking.bonusOrderStar': '⭐ Bonus Order',
    'booking.bonusCommissionLabel': 'Bonus Commission',
    'booking.totalCommissionReceived': 'Total Commission Received',
    'booking.fundsReleasedMsg': 'Locked funds have been released to your wallet.',
    'booking.finish': 'Finish',
    'booking.noHotelFound': 'No Hotels Found',
    'booking.noHotelDesc': 'Try changing your search or location filter.',
    'booking.minNightsLabel': 'Min.',
    'booking.commissionShort': 'Commission',
    'booking.bookBtn': 'Book',
    'booking.pendingWarningTitle': 'You Have an Incomplete Order',
    'booking.pendingWarningDesc': 'You have a pending bonus order that has not been completed. Please complete it before making a new booking.',
    'booking.goToPendingOrder': 'Go to Pending Order',
    'booking.bonusTotalPaid': 'Total Paid',
    'booking.processingStatus': 'Processing...',
    'booking.syncingPlatforms': 'Syncing platform data',
    'booking.processingWait': 'Processing, please wait...',
    'booking.orderSettlement': 'Order Settlement Info',
    'booking.bonusOrderSettlement': 'Bonus Order Settlement Info',
    'booking.orderComplete': 'Order successfully completed',
    'booking.congratsMsg': 'Congratulations! Commission has been successfully settled and will be credited within 24 hours.',
    'booking.hotelName': 'Hotel Name',
    'booking.orderNumber': 'Order No.',
    'booking.secondsLeft': 's left',
    'booking.fullHotel': 'This hotel is currently full and cannot be booked.',
    'booking.orderSettlementDetails': 'Order Settlement Details',
    'booking.progressLabel': 'System Matching Progress',
    'booking.fundsReleasedFull': 'Locked funds have been released to your wallet.',

    // Language switcher
    'lang.ms': 'BM',
    'lang.en': 'EN',
    'lang.zh': '中文',
    'lang.label': 'Language',
  },

  zh: {
    // Nav
    'nav.dashboard': '控制台',
    'nav.hotelBooking': '酒店预订',
    'nav.pastBookings': '预订历史',
    'nav.withdrawalTracker': '提款追踪',
    'nav.walletTopup': '钱包充值',
    'nav.walletWithdrawal': '钱包提款',
    'nav.userManagement': '用户管理',
    'nav.finance': '财务管理',
    'nav.hotelManagement': '酒店管理',
    'nav.adminAccounts': '管理员账户',
    'nav.adminMessages': '站内消息',
    'nav.hotelImport': '导入样本酒店',
    'nav.analytics': '分析仪表板',
    'nav.signOut': '退出登录',
    'nav.mainMenu': '主菜单',
    'nav.adminPanel': '管理面板',

    // Topbar
    'topbar.wallet': '钱包',
    'topbar.islamicBooking': '🕌 IslamicBooking Pro',
    'topbar.adminPanel': '🛡️ 管理面板',

    // Dashboard
    'dashboard.title': '控制台',
    'dashboard.welcome': '欢迎',
    'dashboard.walletBalance': '钱包余额',
    'dashboard.totalCommission': '总佣金',
    'dashboard.totalOrders': '总订单',
    'dashboard.reputation': '信誉',
    'dashboard.level': '等级',
    'dashboard.tasks': '任务',
    'dashboard.recentOrders': '最近订单',
    'dashboard.liveFeed': '实时动态',
    'dashboard.withdraw': '提款',
    'dashboard.topUp': '充值',
    'dashboard.bookNow': '立即预订',
    'dashboard.walletHistory': '钱包历史',
    'dashboard.commissionChart': '佣金图表',
    'dashboard.levelProgress': '等级进度',
    'dashboard.ordersToNextLevel': '订单到下一等级',
    'dashboard.reputationScore': '信誉分数',
    'dashboard.canWithdraw': '可以提款',
    'dashboard.cannotWithdraw': '无法提款',
    'dashboard.reputationWarning': '信誉 < 80 — 无法提款',
    'dashboard.hotel': '酒店',
    'dashboard.amount': '金额',
    'dashboard.commission': '佣金',
    'dashboard.status': '状态',
    'dashboard.date': '日期',
    'dashboard.completed': '已完成',
    'dashboard.bonus': '奖励',
    'dashboard.locked': '已锁定',
    'dashboard.inProgress': '进行中',
    'dashboard.cancelled': '已取消',
    'dashboard.taskProgress': '任务进度',
    'dashboard.reward': '奖励',
    'dashboard.done': '完成',
    'dashboard.pending': '待处理',
    'dashboard.viewAll': '查看全部',
    'dashboard.noOrders': '暂无订单',

    // Hotel Booking
    'booking.title': '酒店预订',
    'booking.selectHotel': '选择酒店',
    'booking.nights': '晚',
    'booking.totalAmount': '总金额',
    'booking.commission': '佣金',
    'booking.bookNow': '立即预订',
    'booking.minDays': '最少晚数',
    'booking.perNight': '/晚',
    'booking.halalCertified': '清真认证',
    'booking.processing': '正在处理预订...',
    'booking.success': '预订成功！',
    'booking.bonusOrder': '奖励订单',
    'booking.bonusMessage': '恭喜！您被选中获得奖励订单。',
    'booking.selectBonusHotel': '请选择奖励订单的酒店：',
    'booking.insufficientBalance': '余额不足',
    'booking.walletBalance': '钱包余额',
    'booking.searchHotel': '搜索酒店...',
    'booking.allHotels': '所有酒店',
    'booking.rating': '评分',
    'booking.location': '位置',
    'booking.confirmBooking': '确认预订',
    'booking.cancel': '取消',
    'booking.confirm': '确认',
    'booking.orderSummary': '订单摘要',
    'booking.originalOrder': '原始订单',
    'booking.bonusOrderLabel': '奖励订单',
    'booking.totalCommission': '总佣金',
    'booking.fundsUnlocked': '资金已解锁',
    'booking.close': '关闭',

    // Past Bookings
    'pastBookings.title': '预订历史',
    'pastBookings.subtitle': '您所有预订的记录',
    'pastBookings.totalBookings': '总预订数',
    'pastBookings.totalPaid': '总付款',
    'pastBookings.totalCommission': '总佣金',
    'pastBookings.hotel': '酒店',
    'pastBookings.checkIn': '入住',
    'pastBookings.checkOut': '退房',
    'pastBookings.nights': '晚',
    'pastBookings.amountPaid': '付款金额',
    'pastBookings.commission': '佣金',
    'pastBookings.status': '状态',
    'pastBookings.orderDate': '订单日期',
    'pastBookings.all': '全部',
    'pastBookings.completed': '已完成',
    'pastBookings.bonus': '奖励',
    'pastBookings.locked': '已锁定',
    'pastBookings.inProgress': '进行中',
    'pastBookings.cancelled': '已取消',
    'pastBookings.search': '搜索酒店或ID...',
    'pastBookings.noResults': '未找到记录',
    'pastBookings.backToDashboard': '返回控制台',
    'pastBookings.pendingCompletion': '待完成',
    'pastBookings.pendingDesc': '尚未完成的奖励订单',
    'pastBookings.noPending': '暂无待处理订单',
    'pastBookings.awaitingCompletion': '等待完成',
    'pastBookings.matchedAt': '匹配于',
    'pastBookings.continueOrder': '继续订单',
    'pastBookings.resumeBonusTitle': '继续奖励订单',
    'pastBookings.resumeBonusDesc': '您的奖励订单正在等待。继续以获得佣金。',
    'pastBookings.processingBonus': '正在处理奖励订单...',
    'pastBookings.bonusComplete': '奖励订单完成！',
    'pastBookings.bonusCompleteDesc': '佣金已添加到您的钱包。',
    'pastBookings.cancelBtn': '取消',
    'pastBookings.done': '完成',

    // Withdrawal Tracker
    'withdrawal.title': '提款追踪',
    'withdrawal.subtitle': '追踪您所有的提款申请',
    'withdrawal.totalApproved': '已批准总额',
    'withdrawal.pendingAmount': '待处理金额',
    'withdrawal.totalRequests': '总申请数',
    'withdrawal.submittedDate': '提交日期',
    'withdrawal.amount': '金额',
    'withdrawal.status': '状态',
    'withdrawal.approvalDate': '批准日期',
    'withdrawal.paymentDetails': '付款详情',
    'withdrawal.bank': '银行',
    'withdrawal.accountNo': '账号',
    'withdrawal.accountHolder': '账户持有人',
    'withdrawal.referenceNo': '参考号',
    'withdrawal.remarks': '备注',
    'withdrawal.all': '全部',
    'withdrawal.approved': '已批准',
    'withdrawal.inProcess': '处理中',
    'withdrawal.pending': '待处理',
    'withdrawal.rejected': '已拒绝',
    'withdrawal.noResults': '未找到记录',
    'withdrawal.backToDashboard': '返回控制台',
    'withdrawal.viewDetails': '查看详情',
    'withdrawal.hideDetails': '隐藏',
    'withdrawal.na': '不适用',
    'withdrawal.pending_approval': '等待批准',
    'withdraw.accountNoRequired': '请输入您的账号',
    'withdraw.amountRequired': '最低提款金额为 RM 50',
    'withdraw.insufficientBalance': '余额不足',
    'withdraw.bankRequired': '请选择您的银行',
    'withdraw.accountHolderRequired': '请输入账户持有人姓名',
    'withdraw.holderNameRequired': '请输入账户持有人姓名',
    'withdraw.title': '钱包提款',
    'withdraw.amount': '提款金额',
    'withdraw.selectBank': '选择银行',
    'withdraw.selectBankPlaceholder': '请选择您的银行',
    'withdraw.accountNumber': '账户号码',
    'withdraw.holderName': '账户持有人姓名',
    'withdraw.holderNamePlaceholder': '与银行账户一致的全名',
    'withdraw.submit': '提交申请',
    'withdraw.submittedTitle': '申请已提交！',
    'withdraw.submittedDesc': '您的提款申请已发送给管理员审核。',
    'withdraw.done': '完成',

    // Top-Up
    'topup.title': '钱包充值',
    'topup.subtitle': '提交充值申请 — 管理员将审核并为您的钱包充值',
    'topup.stepDetails': '详情',
    'topup.stepReview': '确认',
    'topup.stepDone': '完成',
    'topup.amountSection': '充值金额',
    'topup.amountMin': '最低充值金额为 RM 10',
    'topup.methodRequired': '请选择支付方式',
    'topup.bankRequired': '请选择您的银行',
    'topup.paymentMethod': '支付方式',
    'topup.amountTitle': '充值金额',
    'topup.amountPlaceholder': '0.00',
    'topup.amountError': '最低充值金额为 RM 10',
    'topup.methodTitle': '支付方式',
    'topup.methodError': '请选择支付方式',
    'topup.selectBank': '选择您的银行',
    'topup.selectBankPlaceholder': '— 选择银行 —',
    'topup.bankError': '请选择您的银行',
    'topup.referenceSection': '交易参考号',
    'topup.referenceTitle': '交易参考号',
    'topup.referenceOptional': '（可选）',
    'topup.referencePlaceholder': '例如 TXN123456789',
    'topup.receiptSection': '上传收据',
    'topup.receiptTitle': '上传收据',
    'topup.receiptOptional': '（可选）',
    'topup.receiptUploaded': '已上传',
    'topup.receiptClickUpload': '点击上传收据',
    'topup.receiptFormats': 'JPG、PNG 或 PDF',
    'topup.clickToUpload': '点击上传收据',
    'topup.uploadFormats': 'JPG、PNG 或 PDF',
    'topup.uploaded': '已上传',
    'topup.continueBtn': '确认申请',
    'topup.reviewRequest': '确认申请',
    'topup.reviewTitle': '确认您的申请',
    'topup.reviewAmountLabel': '充值金额',
    'topup.reviewMethodLabel': '支付方式',
    'topup.reviewReferenceLabel': '参考号',
    'topup.reviewReceiptLabel': '收据',
    'topup.reviewReceiptNone': '未提供',
    'topup.reviewStatusLabel': '提交后状态',
    'topup.reviewStatusPending': '待审核',
    'topup.reviewInfoMsg': '您的申请将由管理员审核。批准后钱包余额将被充值。',
    'topup.back': '返回',
    'topup.backBtn': '返回',
    'topup.submitRequest': '提交申请',
    'topup.submitBtn': '提交申请',
    'topup.submitting': '提交中...',
    'topup.submittingBtn': '提交中...',
    'topup.submittedTitle': '申请已提交！',
    'topup.submittedDesc': '您的充值申请',
    'topup.submittedDesc2': '已发送给管理员审核。',
    'topup.successTitle': '申请已提交！',
    'topup.successDesc': '您的充值申请',
    'topup.successDescSuffix': '已发送给管理员审核。',
    'topup.requestId': '申请编号',
    'topup.requestIdLabel': '申请编号',
    'topup.adminReviewMsg': '⏱ 管理员将在 1–24 小时内审核您的申请。批准后您将收到通知。',
    'topup.pendingNotice': '⏱ 管理员将在 1–24 小时内审核您的申请。批准后您将收到通知。',
    'topup.submitAnother': '提交另一个申请',
    'topup.submitAnotherBtn': '提交另一个申请',
    'topup.historyTitle': '我的充值记录',
    'topup.noHistory': '暂无充值申请',
    'topup.historyEmpty': '暂无充值申请',
    'topup.statusApproved': '已批准',
    'topup.statusPending': '待处理',
    'topup.statusRejected': '已拒绝',
    'topup.toastLoginRequired': '请登录后提交充值申请',
    'topup.toastSuccess': '充值申请提交成功！',
    'topup.toastFailed': '充值申请提交失败',
    'topup.enterAmountDesc': '请输入您希望充值到钱包的金额。',
    'topup.depositAmount': '存款金额',
    'topup.continue': '继续',
    'topup.waitingTitle': '等待银行信息',
    'topup.waitingDesc': '管理员将提供您转账所需的银行信息。',
    'topup.supportedBanks': '支持的银行：',
    'topup.adminWillProvide': '提交金额后，管理员将提供银行账号。',
    'topup.bankInfoReceived': '已收到银行信息',
    'topup.bankName': '银行名称',
    'topup.accountNumber': '账号',
    'topup.accountHolder': '账户持有人',
    'topup.transferAmount': '转账金额',
    'topup.uploadReceipt': '上传收据',
    'topup.pleaseUploadReceipt': '请上传您的付款收据',
    'topup.receiptSubmitted': '收据提交成功！',
    'topup.submitReceipt': '提交收据',
    'topup.reviewNotice': '⏱ 管理员将在 1–24 小时内审核您的收据并为您的钱包充值。',
    'topup.done': '完成',

    // Admin
    'admin.users': '用户',
    'admin.search': '搜索...',
    'admin.all': '全部',
    'admin.active': '活跃',
    'admin.frozen': '已冻结',
    'admin.level': '等级',
    'admin.wallet': '钱包',
    'admin.reputation': '信誉',
    'admin.orders': '订单',
    'admin.status': '状态',
    'admin.actions': '操作',
    'admin.freeze': '冻结',
    'admin.unfreeze': '解冻',
    'admin.editWallet': '编辑钱包',
    'admin.editReputation': '编辑信誉',
    'admin.save': '保存',
    'admin.cancel': '取消',
    'admin.topupRequests': '充值申请',
    'admin.withdrawalRequests': '提款申请',
    'admin.walletLogs': '钱包日志',
    'admin.approve': '批准',
    'admin.reject': '拒绝',
    'admin.process': '处理',
    'admin.hotels': '酒店',
    'admin.addHotel': '添加酒店',
    'admin.editHotel': '编辑酒店',
    'admin.deleteHotel': '删除酒店',
    'admin.globalSettings': '全局设置',
    'admin.bonusEligible': '奖励资格',
    'admin.pricePerNight': '每晚价格',
    'admin.minDays': '最少天数',
    'admin.commission': '佣金',
    'admin.halalTags': '清真标签',

    // Admin User Management
    'admin.totalMembers': '总会员数',
    'admin.activeAccounts': '活跃账户',
    'admin.frozenAccounts': '已冻结账户',
    'admin.lowReputation': '信誉 < 80',
    'admin.export': '导出',
    'admin.allStatus': '所有状态',
    'admin.allLevel': '所有等级',
    'admin.searchPlaceholder': '搜索姓名、邮箱、用户ID...',
    'admin.user': '用户',
    'admin.walletBalance': '钱包余额',
    'admin.joinDate': '注册日期',
    'admin.selectedUsers': '用户已选择',
    'admin.freezeAll': '全部冻结',
    'admin.showing': '显示',
    'admin.of': '共',
    'admin.users_label': '用户',
    'admin.editWalletTitle': '编辑钱包',
    'admin.currentBalance': '当前余额',
    'admin.operationType': '操作类型',
    'admin.addBalance': '+ 增加余额',
    'admin.deductBalance': '− 扣除余额',
    'admin.amount': '金额 (RM)',
    'admin.adminNote': '管理员备注',
    'admin.noteDesc': '钱包修改原因记录',
    'admin.notePlaceholder': '例如：手动充值批准、罚款等...',
    'admin.updateWallet': '更新钱包',
    'admin.editReputationTitle': '编辑信誉',
    'admin.currentReputation': '当前信誉',
    'admin.reputationWarningAdmin': '信誉低于80将阻止该用户提款。',
    'admin.newReputationValue': '新信誉值 (0–100)',
    'admin.reasonForChange': '修改原因',
    'admin.reasonPlaceholder': '例如：违反服务条款、退款等...',
    'admin.updateReputation': '更新信誉',
    'admin.lowReputationBadge': '低信誉',
    'admin.activateAccount': '激活账户',
    'admin.freezeAccount': '冻结账户',

    // Active Booking Monitor
    'admin.activeBookingMonitor': '实时预订监控',
    'admin.activeBookingSubtitle': '正在实时进行预订的用户',
    'admin.activeNow': '正在活跃',
    'admin.noActiveBookings': '暂无活跃预订',
    'admin.noActiveBookingsDesc': '当前没有用户正在进行预订',
    'admin.bookingNow': '预订中',
    'admin.bookingHotel': '酒店',
    'admin.bookingAmount': '金额',
    'admin.bookingElapsed': '已用时间',
    'admin.dispatchBonus': '派发福利订单',
    'admin.dispatchBonusTitle': '向该用户派发福利订单',
    'admin.blockTransaction': '禁止交易',
    'admin.blockTransactionTitle': '封锁并冻结该用户账户',
    'admin.bonusDispatched': '福利订单已派发',
    'admin.transactionBlocked': '交易已禁止',

    // Admin Finance
    'admin.financeTitle': '财务管理',
    'admin.financeSubtitle': '充值、提款和交易日志',
    'admin.topupPending': '充值待处理',
    'admin.withdrawalPending': '提款待处理',
    'admin.topupToday': '今日充值',
    'admin.withdrawalToday': '今日提款',
    'admin.pendingApproval': '待批准',
    'admin.commissionRate': '佣金率',
    'admin.financialFlow': '7天财务流水',
    'admin.financialFlowSubtitle': '充值、提款和佣金',
    'admin.globalCommissionSettings': '全局佣金设置',
    'admin.globalCommissionDesc': '此费率适用于所有酒店',
    'admin.commissionRateLabel': '佣金率 (%)',
    'admin.currentCommissionDesc': '此平台所有酒店预订的当前佣金率',
    'admin.topupRequests': '充值申请',
    'admin.withdrawalRequests': '提款申请',
    'admin.transactionLogs': '交易日志',
    'admin.method': '方式',
    'admin.reference': '参考号',
    'admin.date': '日期',
    'admin.accountNo': '账号',
    'admin.sendBankInfo': '发送银行信息',
    'admin.approveToplup': '批准充值',
    'admin.rejectRequest': '拒绝申请',
    'admin.rejectWithdrawal': '拒绝提款',
    'admin.approveWithdrawal': '批准提款',
    'admin.recentTransactionLogs': '最近交易日志',
    'admin.allWalletMovements': '所有用户钱包余额变动',
    'admin.balance': '余额',
    'admin.bankInfoModalTitle': '发送银行信息',
    'admin.bankInfoTo': '发送给',
    'admin.bankInfoDesc': '用户需要转账到以下账户。收到凭证后，批准他们的充值。',
    'admin.bankName': '银行名称',
    'admin.accountNumber': '账户号码',
    'admin.accountHolderName': '账户持有人姓名',
    'admin.additionalInstructions': '附加说明',
    'admin.additionalInstructionsPlaceholder': '例如：请注明全名作为参考...',
    'admin.sendInfo': '发送信息',
    'admin.rejectConfirmTitle': '拒绝申请？',
    'admin.rejectConfirmDesc': '该用户的申请将被拒绝，用户将收到通知。',
    'admin.yesReject': '是，拒绝',
    'admin.topup': '充值',
    'admin.withdrawal': '提款',

    // Admin Hotel Management
    'admin.hotelTitle': '酒店管理',
    'admin.hotelSubtitle': '酒店 · 活跃 · 奖励资格',
    'admin.addHotelBtn': '添加酒店',
    'admin.editHotelBtn': '编辑酒店',
    'admin.deleteHotelBtn': '删除酒店',
    'admin.totalHotels': '总酒店数',
    'admin.activeHotels': '活跃酒店',
    'admin.bonusEligibleHotels': '奖励资格',
    'admin.inactiveHotels': '未激活',
    'admin.searchHotelPlaceholder': '搜索酒店或位置...',
    'admin.allFilter': '全部',
    'admin.activeFilter': '活跃',
    'admin.inactiveFilter': '未激活',
    'admin.location': '位置',
    'admin.pricePerNightLabel': '价格/晚',
    'admin.minDaysLabel': '最少天数',
    'admin.commissionLabel': '佣金',
    'admin.bonusLabel': '奖励',
    'admin.activeLabel': '活跃',
    'admin.createdAt': '创建时间',
    'admin.editHotelTitle': '编辑酒店',
    'admin.addHotelTitle': '添加新酒店',
    'admin.hotelName': '酒店名称',
    'admin.hotelLocation': '位置',
    'admin.pricePerNightForm': '每晚价格 (RM)',
    'admin.minDaysForm': '最少天数',
    'admin.commissionForm': '佣金率 (%)',
    'admin.halalTagsForm': '清真标签（逗号分隔）',
    'admin.halalTagsPlaceholder': '例如：清真食品、祈祷室、无酒精',
    'admin.bonusEligibleForm': '奖励订单资格',
    'admin.activeForm': '酒店活跃',
    'admin.saveHotel': '保存酒店',
    'admin.updateHotel': '更新酒店',
    'admin.saving': '保存中...',
    'admin.deleteHotelTitle': '删除酒店？',
    'admin.deleteHotelDesc': '此酒店将被永久删除。此操作无法撤销。',
    'admin.yesDelete': '是，删除',
    'admin.globalSettingsTitle': '全局酒店设置',
    'admin.globalSettingsDesc': '留空任何字段以保留酒店当前值。',
    'admin.globalPriceLabel': '全局每晚价格 (RM)',
    'admin.globalMinDaysLabel': '全局最少天数',
    'admin.globalCommissionLabel': '全局佣金率 (%)',
    'admin.applyToAll': '应用到所有酒店',

    // Hotel Booking modal strings
    'booking.bookingDetails': '预订详情',
    'booking.numberOfNights': '晚数',
    'booking.minimumNights': '此酒店最少晚数',
    'booking.nights_label': '晚',
    'booking.perNightLabel': '/晚',
    'booking.commissionLabel': '佣金',
    'booking.totalDeducted': '扣除总额',
    'booking.walletSufficient': '充足',
    'booking.walletInsufficient': '不足',
    'booking.walletBalanceLabel': '钱包余额',
    'booking.proceed': '继续',
    'booking.processingTitle': '正在处理预订',
    'booking.processingDesc': '正在与国际平台核查可用性...',
    'booking.percentComplete': '% 完成',
    'booking.bookingSuccessTitle': '预订成功！',
    'booking.orderNo': '订单号',
    'booking.totalPaid': '总付款',
    'booking.commissionReceived': '已获佣金',
    'booking.bonusSelectedTitle': '您被选中获得奖励订单！',
    'booking.bonusSelectedDesc': '完成奖励订单以解锁您的资金',
    'booking.bonusLockedWarning': '您第一笔订单的资金已被锁定，直到完成此奖励订单。',
    'booking.selectBonusHotelLabel': '请选择奖励订单的酒店：',
    'booking.bonusCommission': '佣金',
    'booking.selectBtn': '选择',
    'booking.bonusCannotSkip': '奖励订单不可跳过。如有问题请联系客服。',
    'booking.bonusProcessingTitle': '正在处理奖励订单',
    'booking.bonusProcessingDesc': '第一笔订单资金正在一起处理...',
    'booking.bothOrdersComplete': '两笔订单均已完成！',
    'booking.bothOrdersDesc': '锁定资金已释放 · 佣金已合并',
    'booking.originalOrderLabel': '原始订单',
    'booking.bonusOrderStar': '⭐ 奖励订单',
    'booking.bonusCommissionLabel': '奖励佣金',
    'booking.totalCommissionReceived': '已获总佣金',
    'booking.fundsReleasedMsg': '锁定资金已释放到您的钱包。',
    'booking.finish': '完成',
    'booking.noHotelFound': '未找到酒店',
    'booking.noHotelDesc': '请尝试更改搜索或位置筛选。',
    'booking.minNightsLabel': '最少',
    'booking.commissionShort': '佣金',
    'booking.bookBtn': '预订',
    'booking.pendingWarningTitle': '您有一个尚未完成的订单',
    'booking.pendingWarningDesc': '您有一个待完成的福利订单尚未处理。请先完成该订单，再进行新的预订。',
    'booking.goToPendingOrder': '前往待完成订单',
    'booking.bonusTotalPaid': '总付款',
    'booking.processingStatus': '正在处理...',
    'booking.syncingPlatforms': '正在同步平台数据',
    'booking.processingWait': '正在处理，请稍候...',
    'booking.orderSettlement': '订单结算信息',
    'booking.bonusOrderSettlement': '奖励订单结算信息',
    'booking.orderComplete': '订单成功完成',
    'booking.congratsMsg': '恭喜！佣金已成功结算，将在24小时内入账。',
    'booking.hotelName': '酒店名称',
    'booking.orderNumber': '订单号',
    'booking.secondsLeft': '秒后',
    'booking.fullHotel': '该酒店目前已满，无法预订。',
    'booking.orderSettlementDetails': '订单结算详情',
    'booking.progressLabel': '系统匹配进度',
    'booking.fundsReleasedFull': '锁定资金已释放到您的钱包。',

    // Language switcher
    'lang.ms': 'BM',
    'lang.en': 'EN',
    'lang.zh': '中文',
    'lang.label': '语言',
  },
};

// ─── Provider ─────────────────────────────────────────────────────────────────
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('zh');

  const setLang = useCallback((newLang: Lang) => {
    setLangState(newLang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('ibp_lang', newLang);
    }
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[lang][key] ?? translations['zh'][key] ?? key;
    },
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextType {
  return useContext(LanguageContext);
}
